"""add_user_id_to_domain_events

Revision ID: 9fdc2aedeb71
Revises: 20260508_email_otp
Create Date: 2026-05-14 00:37:36.724845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fdc2aedeb71'
down_revision: Union[str, Sequence[str], None] = '20260508_email_otp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_email_otps_user_id'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_table('alembic_version_ai')
    op.add_column('domain_events', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_domain_events_user_id'), 'domain_events', ['user_id'], unique=False)
    op.alter_column('event_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('event_types_name_key'), 'event_types', type_='unique')
    op.drop_index(op.f('ix_event_types_is_active'), table_name='event_types')
    op.create_index(op.f('ix_event_types_id'), 'event_types', ['id'], unique=False)
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=5000),
               existing_nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('events', 'special_requirements',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=True)
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('draft', 'planned', 'active', 'completed', 'canceled', name='event_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'draft'::event_status_enum"))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.drop_constraint(op.f('events_user_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('booking_created', 'booking_confirmed', 'booking_cancelled', 'booking_completed', 'booking_rejected', 'booking_status_changed', 'system', 'event_created', 'event_status_changed', 'event_cancelled', 'vendor_approved', 'vendor_rejected', name='notificationtype'),
               existing_nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.add_column('vendor_availability', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.alter_column('vendor_availability', 'locked_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('vendor_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_vendor_availability_status'), table_name='vendor_availability')
    op.drop_constraint(op.f('vendor_availability_booking_id_fkey'), 'vendor_availability', type_='foreignkey')
    op.drop_constraint(op.f('vendor_availability_vendor_id_fkey'), 'vendor_availability', type_='foreignkey')
    op.drop_constraint(op.f('vendor_availability_service_id_fkey'), 'vendor_availability', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_availability', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'vendor_availability', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'vendor_availability', 'vendors', ['vendor_id'], ['id'])
    op.drop_index(op.f('ix_vendor_embeddings_embedding_hnsw'), table_name='vendor_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('vendor_embeddings_vendor_id_key'), 'vendor_embeddings', type_='unique')
    op.drop_index(op.f('ix_vendor_embeddings_vendor_id'), table_name='vendor_embeddings')
    op.create_index(op.f('ix_vendor_embeddings_vendor_id'), 'vendor_embeddings', ['vendor_id'], unique=True)
    op.drop_constraint(op.f('vendor_embeddings_vendor_id_fkey'), 'vendor_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_embeddings', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('vendor_embeddings_vendor_id_fkey'), 'vendor_embeddings', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vendor_embeddings_vendor_id'), table_name='vendor_embeddings')
    op.create_index(op.f('ix_vendor_embeddings_vendor_id'), 'vendor_embeddings', ['vendor_id'], unique=False)
    op.create_unique_constraint(op.f('vendor_embeddings_vendor_id_key'), 'vendor_embeddings', ['vendor_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_vendor_embeddings_embedding_hnsw'), 'vendor_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'vendor_availability', type_='foreignkey')
    op.drop_constraint(None, 'vendor_availability', type_='foreignkey')
    op.drop_constraint(None, 'vendor_availability', type_='foreignkey')
    op.create_foreign_key(op.f('vendor_availability_service_id_fkey'), 'vendor_availability', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('vendor_availability_vendor_id_fkey'), 'vendor_availability', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vendor_availability_booking_id_fkey'), 'vendor_availability', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_vendor_availability_status'), 'vendor_availability', ['status'], unique=False)
    op.alter_column('vendor_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_availability', 'locked_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('vendor_availability', 'notes')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notifications', 'body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('booking_created', 'booking_confirmed', 'booking_cancelled', 'booking_completed', 'booking_rejected', 'booking_status_changed', 'system', 'event_created', 'event_status_changed', 'event_cancelled', 'vendor_approved', 'vendor_rejected', name='notificationtype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_user_id_fkey'), 'events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('draft', 'planned', 'active', 'completed', 'canceled', name='event_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'draft'::event_status_enum"))
    op.alter_column('events', 'special_requirements',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('events', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_event_types_id'), table_name='event_types')
    op.create_index(op.f('ix_event_types_is_active'), 'event_types', ['is_active'], unique=False)
    op.create_unique_constraint(op.f('event_types_name_key'), 'event_types', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('event_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_domain_events_user_id'), table_name='domain_events')
    op.drop_column('domain_events', 'user_id')
    op.create_table('alembic_version_ai',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_ai_pkc'))
    )
    op.create_table('email_otps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('email_otps_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_otps_pkey'))
    )
    op.create_index(op.f('ix_email_otps_user_id'), 'email_otps', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey')),
    sa.UniqueConstraint('user_id', 'notification_type', name=op.f('uq_user_notification_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###
